/**
 * Indexer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package indexer.codegen

import kotlinx.serialization.Serializable

/**
 *
 * @param address
 * @param subaccountNumber
 * @param equity
 * @param freeCollateral
 * @param openPerpetualPositions
 * @param assetPositions
 * @param marginEnabled
 * @param updatedAtHeight
 * @param latestProcessedBlockHeight
 */
@Serializable
data class IndexerSubaccountResponseObject(

    val address: kotlin.String,
    val subaccountNumber: kotlin.Int,
    val equity: kotlin.String,
    val freeCollateral: kotlin.String,
    val openPerpetualPositions: Map<String, IndexerPerpetualPositionResponseObject>,
    val assetPositions: Map<String, IndexerAssetPositionResponseObject>,
    val marginEnabled: kotlin.Boolean,
    val updatedAtHeight: kotlin.String,
    val latestProcessedBlockHeight: kotlin.String
)
